name: Docker SSLH http-old

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker buildx multiarch
      run: |
        docker buildx create --name multiarch
        docker buildx use multiarch
        docker buildx inspect --bootstrap
        
    - name: docker build sslh http-old
      run: |
        sudo apt update
        sudo apt install dos2unix -y
        sudo dos2unix entrypoint.sh
        docker buildx build ./http -t archef2000/sslh:http-old --platform linux/amd64,linux/arm/v7,linux/arm64 --push
